---
title: "Vorlage Seminararbeit ResProj"
output: html_document
date: '2022-06-21'
editor_options: 
  chunk_output_type: console
---


Hallo, hier spricht ein Mensch.

# Tabellen exportieren


## mit `kable()`

```{r}
library(tidyverse)
library(knitr)
```


```{r}
data(mtcars)
```

```{r}
mtcars_short <- 
mtcars %>% 
  slice(1:10) %>% 
  select(1:3)
  
mtcars %>% 
  kable()
```


## Mit `apatables`


```{r}
library(apaTables)
```

```{r}
apa.cor.table(mtcars_short, filename = "apa_test1.docx", table.number = 1)
```


# Diagramme


```{r}
library(rstanarm)
lm1 <- stan_glm(mpg ~ hp, data = mtcars, refresh = 0)
```


```{r}
library(easystats)
```

```{r}
parameters(lm1)
```


```{r }
plot1  <- plot(parameters(lm1))
plot1
```

Bild explizit abspeichern:

```{r}
ggsave(plot = plot1, filename = "plot1.png")
```


# Theme minimal bei ggplot



```{r}
ggplot(mtcars, aes(x = mpg)) + geom_density() +
  theme_minimal()
```




# Faktorstufen umsortieren



```{r}
d <-
  tibble(i01 = c("stimme voll und ganz zu", "stimme eher zu", "stimme überhaupt nicht zu"),
         i01f = factor(i01, levels = c("stimme überhaupt nicht zu", "stimme eher nicht zu", "stimme eher zu", "stimme voll und ganz zu")))
```



# ANOVA und Signifikanz

```{r}
aov1 <- aov(mpg ~  hp + cyl, data = mtcars)
aov1
```


```{r}
apa.aov.table(aov1, filename = "Table4_APA.doc", table.number = 4)
```

# LM berichten mit APA-Tables


```{r}
lm1 <- lm(mpg ~  hp + cyl, data = mtcars)
lm1
apa.reg.table(lm1, filename = "table5_apa.doxc", table.number = 5)
```


