---
title: "Kap. 10.6"
format: html
date: today
---

# Pakete starten

```{r}
library(tidyverse)
library(easystats)
library(yardstick)  # Vorhersagegüte bestimmen
library(ggstatsplot)  # Datenbilder
```


# Daten importieren




Train-Datensatz:

```{r}
mariokart_train <- read.csv("https://raw.githubusercontent.com/sebastiansauer/statistik1/main/daten/mariokart_train.csv")
```

Importieren von der Festplatte:

```{r}
mariokart_train <- read.csv("data/mariokart_train.csv")
```



Test-Datensatz:

```{r}
mariokart_test <- read.csv("https://raw.githubusercontent.com/sebastiansauer/statistik1/main/daten/mariokart_test.csv")
```

oder:

```{r}
mariokart_test <- read.csv("data/mariokart_test.csv")
```



# Modell 1 (All-in)

```{r}
lm_allin <- lm(total_pr ~ ., data = mariokart_train)
```

Modellgüte - MAE im Train-Sample:

```{r}
performance::mae(lm_allin)
```


```{r}
r2(lm_allin)
```


Vorhersagen:

```{r}
mariokart_test <-
  mariokart_test %>% 
  mutate(lm_allin_predictions = predict(lm_allin, newdata = mariokart_test)) %>% 
  relocate(lm_allin_predictions, .after = total_pr)
```

Güte der Vorhersagen:

```{r}
library(yardstick)

yardstick::mae(data = mariokart_test,
               truth = total_pr,  # echter Verkaufspreis
               estimate = lm_allin_predictions)  # Ihre Vorhersage
```


## Modell 2

Daten visualisieren:

```{r}
gghistostats(
  data = mariokart_train,
  x = total_pr
)
```



```{r}
mariokart_train2 <- 
  mariokart_train %>% 
  filter(total_pr < 100) %>% 
  select(-id, X)
```


```{r}
lm2 <- lm(total_pr ~ ., data = mariokart_train2)
```

Modellgüte:

```{r}
r2(lm2)
```


Vorhersagen:



```{r}
mariokart_test <-
  mariokart_test %>% 
  mutate(lm2_pred = predict(lm2, newdata = mariokart_test))
```

Vorhersagegüte:

```{r}
yardstick::mae(
  data = mariokart_test,
  truth = total_pr,
  estimate = lm2_pred
)
```
Vorhersagegüte (R-Quadrat):

```{r}
rsq(  # auch aus dem Paket `yeardstick`:
   data = mariokart_test,
  truth = total_pr,
  estimate = lm2_pred
)
```

