---
title: "20260922 - Introduction to statistical modeling"
format: html
---


# Welcome!


# Quick start


Load R packages:

Use `Alt+Command+I` to *I*nsert a Code Chunk:

```{r}

```




```{r}
library(tidyverse)  
library(easystats)
```

Load data:


```{r}
d <- read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/palmerpenguins/penguins.csv")

head(d)  # see the first few rows, the "head" of the table
```


First Modelling:


```{r}
m1 <- lm(body_mass_g ~ bill_length_mm, data = d)  # Control+Enter

model_parameters(m1)
```

$R^2$: The (percentage) amount of explained variance of the model - "goodness" of the model.

```{r}
r2(m1)
```


Standardized coefficients:

```{r}
effectsize::standardize_parameters(m1, method = "refit")   # oder "basic"
```

Visualize the model:

```{r}
library(ggpubr)  #control+enter

ggscatter(d, 
          x = "bill_length_mm",
          y = "body_mass_g",
          add = "reg.line")
```




# Exercise

Choose and run your own model, just as above. Try to understand the result.





