---
title: Besonderheiten von Gruppenarbeiten
author: Sebastian Sauer
---




Bei einer Gruppenarbeit wird ein Projekt, etwa eine empirische Studie oder eine Datenanalyse von mehreren Personen bearbeitet.

Neben der inhaltlich-methodischen Kompetenz soll im Rahmen dieser Prüfungsform abgeprüft werden, ob und wieweit sich die Studierenden mit den sozialdynamischen Prozessen erfolgreich auseinander setzen können. Dies ist vor dem Hintergrund der Allgegenwärtigkeit von Arbeitsgruppen im Berufsleben begründet. Für die berufliche Ausbildung ist es wichtig, Erfahrung mit den Vorzügen aber Schwierigkeiten von Arbeitsgruppen vertraut gemacht zu haben.
Eine Prüfungsleistung an der Hochschule bietet dafür einen geschützten Rahmen.



- Jedes Kapitel (erste Gliederungsebene) oder jeder Abschnitt (zweite Gliederungsebene) ist mit dem Namen der verantwortlichen Person auszuweisen. 
- Jedes Mitglieder einer Arbeitsgruppe erhält eine eigene, individuelle Note. 
- Die Noten der Gruppenglieder müssen daher nicht identisch sein (können aber).
- Alle Kommentare des Gutachters sind mit dem Namen (bzw. Namenskürzel) derjenigen Person versehen, an die der Kommentar gerichtet ist.
- In die Note (eines bestimmten Gutachtens) fließen nur Abschnitt ein, die von der/dem angegebenen Verfasser:in verfasst wurden sowie diejenigen Abschnitte, die nicht namentlich gekennzeichnet wurden (nur relevant bei Gruppenarbeiten). Kommentare zu Abschnitten, die ohne Namen in der Prüfungsleistung angegeben sind, werden auch ohne Namenshinweis aufgeführt.
- Die Mitglieder einer Arbeitsgruppe sind angehalten, auf die Vergleichbarkeit der Beiträge zu achten.
- Unterschiedliche Ansichten zum Vorgehen sind zuerst innerhalb der Gruppe zu klären. Falls dies erfolglos ist, soll (wenn nötig) der Dozent angesprochen werden. Zu beachten sind, dass das Moderieren des Gruppenprozesses Teil der Prüfungsleistung ist. 
- Der Dozent gibt i.d.R. ein einzelnes Gutachten für eine Projektleistung (wie eine Studie) zurück, um der Integrität des Werkes Rechnung zu tragen. Allerdings sind die Noten und die Beurteilungshinweisen separat für jedes Mitglied der Arbeitsgruppe ausgewiesen. 

