


## Didaktik


### Grundlagen

1. Alle Lehrmaterialien stelle ich vor dem Unterricht online bereit
2. Alles prüfungsrelevante Material ist verschriftlicht
3. Die Prüfungsmodalitäten sind frühzeitig (schriftlich) bekannt gemacht
4. Jedes Modul ist auch ohne Besuchen des Unterrichts studierbar
5. Wenn möglich, wird der Präsenzunterricht durch Live-Streaming ergänzt
6. Für den Stoff existiert eine Gliederung und Lernziele, so dass ein roter Faden ersichtlich ist
7. Für jede Unterrichtseinheit ist ein Thema vorgegeben
8. Es werden für (möglichst) alle Unterrichtseinheiten Aufgaben bereitgestellt
9. Praxisbezug wird sichergestellt, z.B. durch Fallstudien
10. Infos an die Studierenden eines Moduls werden durch ein Nachrichtensystem zugestellt.



    

### Lehrkonzept

- In der "Vorlesung" wird im Schwerpunkt *nicht* ein Folienskript "vorgelesen". Dieser Vortrag steht oft vorab als Video zur Verfügung (s. Links im Themenüberblick).
- Stattdessen steht in der "Vorlesung" die Durcharbeiten und Vertiefen des Stoffes im Vordergrund, nicht aber das Vortragen des Stoffes.
- Warum wird die Literatur oder das Folienskript nicht im Unterricht vorgetragen? Zum einen können Sie das alleine besser (in eigener Geschwindigkeit, mit Pausen nach Gusto, zu beliebiger Zeit und beliebigem Ort, so oft wiederholt wie Sie mögen). Zum anderen ist der Lerngewinn beim passiven Zuhören gering. Das Durchdenken, Durcharbeiten, "Durchfragen" des Stoffes ist es, was Ihnen den meisten Gewinn beschwert. Entsprechend liegt auf dem aktiven, gemeinsamen Arbeiten der Schwerpunkt.
- Das heißt nicht, dass es nie Vorträge vom Dozenten im Unterricht gäbe; manchmal schon. Aber aus genannten Gründen liegt der Fokus des Unterrichts im aktivierenden Arbeiten.
- Natürlich können im Unterricht jederzeit die Fragen der Studentis zum Stoff besprochen werden. Seien Sie ausdrücklich ermuntert, Ihre Fragen im Unterricht zu formulieren, vorzugsweise im direkten Gespräch, aber alternativ anonym (wie Frag-Jetzt).
- In der Übung liegt der Schwerpunkt zumeist auf dem Bearbeiten von Aufgaben.



### Lerntipps

- Damit Sie vom Unterricht maximal profitieren, ist es essenziell, dass Sie aktiv mitarbeiten. Ein "Nur-Zuhören" nimmt Ihnen einen Gutteil des Nutzens des Unterrichts. Sie lernen nur zum kleinen Teil vom Zuhören; der größte Teil des Lernerfolgs kommt vom Selber-Erarbeiten!
- Bitte stellen Sie Ihre Kamera (Webcam) an, wenn Sie Kommilitonis oder den Dozenten ansprechen. Das ist der Güte der Kommunikation zuträglich.
- Bereiten Sie den Stoff vor und arbeiten Sie ihn gewissenhaft nach.
- Das gemeinsame Arbeiten in einer (virtuellen) Lerngruppe ist sehr nützlich.
- Tauschen Sie sich im Diskussionsforum auf unserer Modulseite aus; gehen Sie in den Diskurs mit den Kommiliton/innen. Falls Sie (im Internet) nützliches Material gefunden haben, können Sie es auch in das Forum einstellen. 
- Nutzen Sie das Diskussionsforum auch, um den Dozenten Fragen zu stellen. 
- Meine Erfahrung zeigt mir, dass der Lernerfolg zwar auch von der Lehrperson abhängt, aber entscheidend ist der Wille eines/r Studierenden/r, selbst aktiv zu lernen. Ich glaube, dass Sie gut mit Material ausgestattet sind, um selbständig und mit Erfolg zu lernen.
- Anbieter wie Google stellen (teilweise) kostenfreie Angebote zum kollaborativen Arbeiten zur Verfügung (Google Docs). Behalten Sie hier den Datenschutz im Blick.

