

<!-- # Statistik 1 -->


<!-- ## Was lerne ich hier und wozu ist das gut? -->

## Was lerne ich hier?

Sie lernen die Grundlagen der Datenanalyse mit einem Schwerpunkt auf Vorhersage. 
Anders gesagt: Sie lernen, wie man aus Daten Vorhersagen ableitet. Zum Beispiel: Kommt ein Student zu Ihnen und sagt "Ich habe 42 Stunden für die Klausur gelernt, welche Note kann ich in der Klausur erwarten?".
Darauf Ihre Antwort: "Auf Basis meiner Daten und meines Modells müsstest du eine 2.7 schreiben!". (Darauf dis Studenti: "Hpmf.").
Außerdem lernen Sie, wie man die Güte einer Vorhersage auf Stichhaltigkeit prüft. 
Denn Vorhersagen kann man ja in jeder Eckkneipe oder beim Wahrsager bekommen. 
Wir wollen aber belastbare Vorhersagen und zumindest wissen,
wie gut die Vorhersagen bisher waren.


## Warum ist das wichtig?

Wir wollen nicht auf Leuten vertrauen, die behaupten, sie wüssten, was für uns richtig und gut ist. Wir wollen selber die Fakten prüfen können.

## Wozu brauche ich das im Job?

Datenanalyse spielt bereits heute in vielen Berufen eine Rolle. Tendenz stark zunehmend.

## Wozu brauche ich das im weiterem Studium?

In Forschungsarbeiten (wie in empirischen Forschungsprojekten, etwa in der Abschlussarbeit) ist es üblich, statistische Ergebnisse hinsichtlich quantitativ zu analysieren.

