


<!-- ## Prüfungsformat Kolloquium -->


### Hintergrund und Ziel

Das Prüfungsformat Kolloquium ist eine Kombination aus Referat und mündlicher Prüfung.
Gegenstand ist ein wissenschaftlicher Vortrag Ihrer Seminar-/Projekt- oder Abschlussarbeit sowie eine sich anschließende wissenschaftliche Aussprache.
Während der wisenschaftlichen Aussprache verteidigen Sie Ihre Arbeit gegenüber fachlicher Kritik.

Ziel ist, die Zuhörerschaft vom wissenschaftlichen Wert Ihrer Arbeit zu überzeugen.


### Teil 1: Referat


#### Grundlagen

Im Rahmen des Referats stellen Sie Ihre wissenschaftliche Arbeit vor, begründen Ihr Vorgehen begründen und diskutieren Sie dessen Stärken und Schwächen.

Häufig wird ein Referat durch eine Präsentation (z.B. Powerpoint) unterstützt.
Das ist oft sinnvoll, allerdings sollte der Vortrag im Mittelpunkt, das gesprochene Wort, und nicht der Text auf einer Folie.

Der Aufbau des Referats ist Ihnen überlassen.
Ein bewährtes Vorgehen ist es, das Referat analog zur Gliederung Ihrer wissenschaftlichen Arbeit aufzubauen.


#### Formalia

Die Dauer des Vortrags beträgt 10 Minuten.


### Teil 2: Aussprache


#### Grundlagen

Im Rahmen der wissenschaftlichen Aussprache stellt Ihnen die Lehrkraft Fragen, die die wissenschaftliche Qualität Ihrer auf die Probe stellen. 
Ziel ist, mögliche Bedenken zur wissenschaftlichen Qualität zu explizieren, dann auszuräumen oder anzuerkennen und schließlich zu bewerten und in einen Kontext zu stellen.

#### Formalia

Die Dauer der wissenschaftlichen Aussprache beträgt 10-15 Minuten.


